api_platform:
  title: "Symfony Rest Api"
  description: "Projet Medcabinet | Symfony Rest Api - Angular"
  mapping:
    paths: ["%kernel.project_dir%/src/Entity"]
  patch_formats:
    json: ["application/merge-patch+json"]
  swagger:
    versions: [3]
